// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright (c) 2023 SUSE LLC
//
// Author: Roy Hopkins <rhopkins@suse.de>

// The file igvm.h is generated by concatenating the output of cnfbind
// with the contents of igvm_template.h. You can add definitions in the
// section below by editing igvm_template.h. Anything below the line
// will be overwritten by the next build.

#ifndef IGVM_H
#define IGVM_H

#pragma pack(push, 1)

// ----------------------------------------------------------------
// Add definitions here in igvm_template.h
// ----------------------------------------------------------------
#include <stdint.h>

struct IgvmPageDataFlags {
	uint32_t is_2mb_page : 1;
	uint32_t unmeasured : 1;
	uint32_t reserved : 30;
};

struct RequiredMemoryFlags {
	uint32_t vtl2_protectable : 1;
	uint32_t reserved : 31;
};

#define UINT32_FLAGS_VALUE(x) *((uint32_t*)&(x))

// ----------------------------------------------------------------
// Do not edit anything below this line
// ----------------------------------------------------------------
